# Generated by Django 4.0.4 on 2022-05-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_remove_file_ispublic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
    ]
